services:
  server:
    build:
      context: ./
      dockerfile: ./server.Dockerfile
    container_name: wow-server
    environment:
      SERVER_HOST: ":13371"
      CHALLENGE_TIMEOUT: "15s"
      CHALLENGE_COMPLEXITY: "12"
      READ_TIMEOUT: "30s"
    ports:
      - "13371:13371"
    networks:
      - wow_network

  client:
    build:
      context: ./
      dockerfile: ./client.Dockerfile
    container_name: wow-client
    environment:
      READ_TIMEOUT: "30s"
      SERVER_HOST: "server:13371"
    networks:
      - wow_network
    depends_on:
      - server

networks:
  wow_network:
    driver: bridge
